version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/minigoaltracker
    depends_on:
      - db

  db:
    image: postgres:13
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=minigoaltracker
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: